// <auto-generated />
namespace DemandTool.MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v002 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v002));
        
        string IMigrationMetadata.Id
        {
            get { return "201811301224543_v0.0.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
